#spring.application.name=demo

#spring.datasource.url=jdbc:postgresql://localhost:5432/srp
#spring.datasource.username=postgres
#spring.datasource.password=4416


#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USERNAME}
#spring.datasource.password=${DATASOURCE_PASSWORD}
SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d23k5lili9vc73f6vmb0-a.oregon-postgres.render.com:5432/srp_nvdr
SPRING_DATASOURCE_USERNAME=srp_nvdr_user
SPRING_DATASOURCE_PASSWORD=pktwiOHaBxGRnha5lmvwPWPcuUgAhc4Z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
